### ISSUE TITLE
fcn-8s-pascalcontext_W_and_b.pkl pre trained model not accesible 

### ISSUE THREAD

**Issue by cricket1** [shiba24/deep-learning-for-human-part-discovery-in-images#2]
The URL for the pre-trained model fcn-8s-pascalcontext_W_and_b.pkl  'https://googledrive.com/host/0BxSyYt1jT6LhUlhITjdicDFyNHM' not accessible .I also checked in https://github.com/shiba24/pretrained-model-collections

**Comment by shiba24** [comment]
can you access here https://drive.google.com/open?id=0BxSyYt1jT6LhUlhITjdicDFyNHM ?

**Comment by cricket1** [comment]
Accessible now .thnk u

**Comment by xscjun** [comment]
https://drive.google.com/open?id=0BxSyYt1jT6LhUlhITjdicDFyNHM 
https://googledrive.com/host/0BxSyYt1jT6LhUlhITjdicDFyNHM
both unreachable when I ran the train.py. any other url ?

**Comment by xscjun** [comment]
https://drive.google.com/open?id=0BxSyYt1jT6LhUlhITjdicDFyNHM
https://googledrive.com/host/0BxSyYt1jT6LhUlhITjdicDFyNHM
Both unreachable when I ran the train.py. Any other url ?

**Comment by dheerajpai** [comment]
Thanks a lot for the information!!
